drop table if exists users cascade ;
drop table if exists roles cascade ;
drop table if exists orders cascade ;

create table roles
(
    id      bigint generated by default as identity
        constraint roles_pkey
            primary key,
    name    varchar(100)              not null
        constraint roles_name_key
            unique,
    created timestamp   default now() not null,
    updated timestamp   default now() not null,
    status  varchar(25) default 'ACTIVE':: character varying not null
);

create table users
(
    id         bigint generated by default as identity
        constraint users_pkey
            primary key,
    username   varchar(100)              not null
        constraint users_username_key
            unique,
    email      varchar(255)              not null
        constraint users_email_key
            unique,
    first_name varchar(100)              not null,
    last_name  varchar(100)              not null,
    password   varchar(255)              not null,
    token      varchar(255)              not null,
    created    timestamp   default now() not null,
    updated    timestamp   default now() not null,
    status     varchar(25) default 'ACTIVE':: character varying not null,
    fk_role_id bigint                    not null
        constraint fk_roes_fk_user_id
            references roles
on update restrict on delete cascade
);


insert into roles (created, updated, status, name)
values (now(),now(),'ACTIVE','ROLE_USER');
insert into users (created, updated, status, username, first_name, last_name, email, password, token, fk_role_id)
values (now(), now(), 'ACTIVE', 'Hima', 'Hikmat', 'Mahmudov', 'mahmudov.hima@gmail.com',
        '$2y$12$nhSjTV/AeBkDzgyEe5vIbOZhU0efMZ.oBXYhbW6Ish6Feouln938G', 'token', 1);