create table roles
(
    id      bigint generated by default as identity
        constraint roles_pkey
            primary key,
    name    varchar(100)              not null
        constraint roles_name_key
            unique,
    created timestamp   default now() not null,
    updated timestamp   default now() not null,
    status  varchar(25) default 'ACTIVE' not null
);

create table users
(
    id         bigint generated by default as identity
        constraint users_pkey
            primary key,
    username   varchar(100)              not null
        constraint users_username_key
            unique,
    email      varchar(255)              not null
        constraint users_email_key
            unique,
    first_name varchar(100)              not null,
    last_name  varchar(100)              not null,
    password   varchar(255)              not null,
    token      varchar(255)              not null,
    created    timestamp   default now() not null,
    updated    timestamp   default now() not null,
    status     varchar(25) default 'ACTIVE' not null,
    fk_role_id bigint                    not null
        constraint fk_roes_fk_user_id
            references roles
            on update restrict on delete cascade
);


insert into roles (created, updated, status, name)
values (now(),now(),'ACTIVE','ROLE_USER');
insert into users (created, updated, status, username, first_name, last_name, email, password, token, fk_role_id)
values (now(), now(), 'ACTIVE', 'Hima', 'Hikmat', 'Mahmudov', 'mahmudov.hima@gmail.com',
        '$2y$12$nhSjTV/AeBkDzgyEe5vIbOZhU0efMZ.oBXYhbW6Ish6Feouln938G', 'token', 1);

create table orders
(
    id               bigint generated by default as identity
        constraint orders_pkey
            primary key,
    created          timestamp   default now() not null,
    updated          timestamp   default now() not null,
    status           varchar(25) default 'ACTIVE' not null,
    card_type        varchar(25)               not null,
    card_holder_name varchar(75)               not null,
    card_period      varchar(25)               not null,
    urgent           boolean                   not null,
    fk_user_id       bigint                    not null
        constraint fk_orders_fk_user_id
            references users
            on update restrict on delete cascade,
    codeword         varchar(25)               not null,
    submitted        boolean     default false not null
);

create table card_credentials
(
    id             bigint generated by default as identity
        constraint card_credentials_pkey
            primary key,
    created        timestamp   default now() not null,
    updated        timestamp   default now() not null,
    status         varchar(25) default 'ACTIVE' not null,
    card_number    bigint                    not null,
    account_number varchar(255)              not null,
    fk_order_id    bigint                    not null
        constraint fk_card_credentials_fk_order_id
            references orders
            on update restrict on delete cascade
);

insert into orders(created, updated, status, card_type, card_holder_name, card_period, urgent, fk_user_id, codeword,
                   submitted)
values (now(), now(), 'ACTIVE', 'MC', 'Hikmat Mahmudov', 'YEAR', false, 1, 'guavapay', false);
insert into orders(created, updated, status, card_type, card_holder_name, card_period, urgent, fk_user_id, codeword,
                   submitted)
values (now(), now(), 'ACTIVE', 'VISA', 'Javid Mahmudzade', 'TWO_YEARS', true, 1, 'guavapay', false);